### ISSUE TITLE
get_liste_sections modifier l'argument section_type

### ISSUE THREAD

**Issue by Norsazz** [CNR-Engineering/Crue10_tools#4]
Changer l'argument section_type en texte et non en objet `Section `si possible.

Solution actuelle : 
`sm.get_liste_sections(section_type=section.SectionProfil)`

Solution souhaitée : 
`sm.get_liste_sections(section_type="SectionProfil")`

**Comment by lucduron** [comment]
Hello Pierre,

Merci pour le ticket.
En effet, il faut utiliser la **classe** (et non pas une chaîne de caractères) pour filtrer les types de section (impact sur les 2 méthodes de `SousModele` et `Modele`). Je me suis rendu compte que le commentaire n'était pas très explicite alors je l'ai amélioré.
On pourrait faire le changement proposé mais l'intérêt me semble limité et il existe en fait les 4 méthodes suivantes (pour le `SousModele`) :

- `get_liste_sections_profil`
- `get_liste_sections_idem`
- `get_liste_sections_interpolees`
- `get_liste_sections_sans_geometrie`

Bien à toi,
Luc
